/**
 * Two scaffolder actions build KAgent CRs as template strings and `kubectl apply`
 * them. That makes them a drift pair with the static manifests in
 * kubernetes/kagent/, and an unusually quiet one: the generated side is a
 * TypeScript string, so a rename in kubernetes/kagent/ is invisible to any
 * file-shaped search of that directory.
 *
 * They drifted on 2026-09-03. ADR-0007 consolidated eight per-server
 * RemoteMCPServer CRs into a single `ai-gateway`, all nine static agent
 * manifests were updated, and both generators kept emitting
 * `name: idp-mcp-server`. Nothing failed: `kubectl apply` accepts the Agent
 * happily and KAgent then parks it at `Accepted: False` / `Ready: Unknown`
 * without naming the missing reference.
 *
 * So these tests assert the generated CRs only reference things that exist,
 * reading kubernetes/kagent/ as the source of truth rather than hardcoding
 * names — a hardcoded expectation would have to be updated by the same edit
 * that breaks the code, which is no guard at all.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

import { buildAgentYaml } from '../idpDeployAgent';
import { buildContractAgentYaml } from '../idpSetupContractTesting';

const KAGENT_DIR = path.resolve(__dirname, '../../../../../../../kubernetes/kagent');

function readKagentManifests(): any[] {
  const docs: any[] = [];
  for (const f of fs.readdirSync(KAGENT_DIR).filter(n => n.endsWith('.yaml'))) {
    for (const d of yaml.parseAllDocuments(fs.readFileSync(path.join(KAGENT_DIR, f), 'utf8'))) {
      const o = d.toJS();
      if (o && typeof o === 'object') docs.push(o);
    }
  }
  return docs;
}

function namesOfKind(docs: any[], kind: string): Set<string> {
  return new Set(docs.filter(d => d.kind === kind).map(d => d.metadata?.name).filter(Boolean));
}

/** Every RemoteMCPServer a generated Agent points at, with its toolNames. */
function mcpRefs(agentYaml: string): Array<{ name: string; toolNames: string[] }> {
  const doc = yaml.parse(agentYaml);
  const tools = doc?.spec?.declarative?.tools ?? [];
  return tools
    .filter((t: any) => t?.mcpServer?.kind === 'RemoteMCPServer')
    .map((t: any) => ({ name: t.mcpServer.name, toolNames: t.mcpServer.toolNames ?? [] }));
}

// Both generators, each under an input that turns every optional tool on — a
// builder that emits nothing references nothing and would pass vacuously.
const generated: Array<{ label: string; yaml: string }> = [
  {
    label: 'idpDeployAgent.buildAgentYaml',
    yaml: buildAgentYaml({
      name: 'test-agent',
      description: 'A scaffolded agent',
      modelConfig: 'claude-haiku',
      enableCatalogSearch: true,
      enableMetrics: true,
      enableScaffolding: true,
    }),
  },
  { label: 'idpSetupContractTesting.buildContractAgentYaml', yaml: buildContractAgentYaml() },
];

describe('KAgent CRs generated by scaffolder actions', () => {
  const docs = readKagentManifests();

  it('reads the static manifests it is checking against', () => {
    // Guards the relative path above: if it ever stops resolving, every other
    // assertion here would pass against an empty set and prove nothing.
    expect(docs.length).toBeGreaterThan(0);
    expect(namesOfKind(docs, 'RemoteMCPServer').size).toBeGreaterThan(0);
  });

  it.each(generated)('$label emits parseable YAML with a declarative agent', ({ yaml: y }) => {
    const doc = yaml.parse(y);
    expect(doc.kind).toBe('Agent');
    expect(doc.apiVersion).toBe('kagent.dev/v1alpha2');
    expect(doc.spec?.declarative?.modelConfig).toBeTruthy();
  });

  it.each(generated)('$label only references RemoteMCPServers that exist', ({ yaml: y }) => {
    const defined = namesOfKind(docs, 'RemoteMCPServer');
    const refs = mcpRefs(y);
    expect(refs.length).toBeGreaterThan(0);
    for (const r of refs) {
      expect(Array.from(defined)).toContain(r.name);
    }
  });

  it.each(generated)('$label only references ModelConfigs that exist', ({ yaml: y }) => {
    const defined = namesOfKind(docs, 'ModelConfig');
    const used = yaml.parse(y).spec.declarative.modelConfig;
    expect(Array.from(defined)).toContain(used);
  });

  it('every modelConfig idpDeployAgent can resolve exists', () => {
    // resolveModelConfig is private, so drive it through the public builder for
    // each branch it can take. A provider/model combination that maps to a
    // ModelConfig nobody created fails the same silent way as a bad MCP name.
    const defined = namesOfKind(docs, 'ModelConfig');
    for (const mc of ['claude-haiku', 'claude-sonnet', 'claude-opus', 'openai-prod']) {
      const y = buildAgentYaml({
        name: 'x', description: 'y', modelConfig: mc,
        enableCatalogSearch: true, enableMetrics: false, enableScaffolding: false,
      });
      expect(Array.from(defined)).toContain(yaml.parse(y).spec.declarative.modelConfig);
    }
  });

  it('the tools a generated agent asks for are tools some MCP server actually has', () => {
    // The gateway federates with prefixMode: never, so a toolName here must match
    // a tool name as its own server registered it. A typo produces an agent that
    // reconciles fine and is simply missing a capability.
    const servers = path.resolve(__dirname, '../../../../../../../services');
    const real = new Set<string>();
    for (const d of fs.readdirSync(servers).filter(n => n.endsWith('-mcp-server'))) {
      const src = path.join(servers, d, 'src');
      if (!fs.existsSync(src)) continue;
      for (const f of fs.readdirSync(src).filter(n => n.endsWith('.ts'))) {
        const text = fs.readFileSync(path.join(src, f), 'utf8');
        // Same pattern scripts/validate-mcp-tool-names.py uses, and for the same
        // reason it accepts two receiver names: contract-mcp-server calls it
        // `srv`, everyone else `server`.
        for (const m of text.matchAll(/\b(?:server|srv)\.tool\(\s*['"]([A-Za-z0-9_]+)['"]/g)) {
          real.add(m[1]);
        }
      }
    }
    expect(real.size).toBeGreaterThan(10);

    for (const { label, yaml: y } of generated) {
      for (const r of mcpRefs(y)) {
        for (const t of r.toolNames) {
          expect(`${label}: ${t}`).toBe(real.has(t) ? `${label}: ${t}` : `${label}: <${t} is not a tool any MCP server registers>`);
        }
      }
    }
  });
});
