replicaCount: 1

image:
  repository: localhost:5003/hello-react-srv
  tag: local
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: hello-react-srv.idp.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

env:
  - name: ENVIRONMENT
    value: local

podLabels:
  team: "qa-team"
  cost-center: "eng-platform"
  environment: local
  app.kubernetes.io/part-of: internal-developer-platform

metrics:
  enabled: true
  port: metrics
  path: /metrics

extraPorts:
  - name: metrics
    port: 9113
    targetPort: 9113

extraContainers:
  - name: nginx-exporter
    image: localhost:5003/nginx-prometheus-exporter:1.3.0
    args:
      - --nginx.scrape-uri=http://localhost:8080/nginx_status
    ports:
      - name: metrics
        containerPort: 9113
    livenessProbe:
      httpGet:
        path: /metrics
        port: 9113
      initialDelaySeconds: 5
      periodSeconds: 15
    readinessProbe:
      httpGet:
        path: /metrics
        port: 9113
      initialDelaySeconds: 3
      periodSeconds: 10
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 32Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop: [ALL]
