# Generated by IDP golden path — replace with real tests for ${{ values.repoName }}


def test_placeholder():
    """Replace this placeholder with real assertions."""
    assert True


def test_example_pure_function():
    """Example: test a pure function."""
    def add(a, b):
        return a + b

    assert add(2, 3) == 5
