apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-service
  description: Reference Go service
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=hello-service
    backstage.io/kubernetes-namespace: services
    backstage.io/techdocs-ref: dir:../../../services/hello-service
    backstage.io/runbook-url: https://github.com/moatazeldebsy/backstage-idp-starter/blob/main/docs/runbooks/index.md
    github.com/project-slug: moatazeldebsy/backstage-idp-starter
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: internal-developer-platform
