apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: my-eks-cluster
  description: EKS cluster my-eks-cluster (k8s 1.31) in us-east-1
  annotations:
    backstage.io/managed-by-location: url:https://github.com/moatazeldebsy/backstage-platform-template/blob/main/terraform/infra/eks-clusters/my-eks-cluster/
  labels:
    aws-region: us-east-1
    kubernetes-version: 1.31
  tags:
    - eks
    - kubernetes
    - aws
spec:
  type: kubernetes-cluster
  owner: group:default/platform-team
  system: internal-developer-platform
