default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy_testflight do
    build_app(
      scheme: ENV["SCHEME"] || "Release",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "app.ipa"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :deploy_app_store do
    build_app(
      scheme: ENV["SCHEME"] || "Release",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "app.ipa"
    )
    upload_to_app_store(
      skip_waiting_for_build_processing: true,
      submit_for_review: false,
      force: true,
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end

platform :android do
  desc "Deploy to Google Play"
  lane :deploy_google_play do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android/"
    )
    upload_to_play_store(
      track: "${{ values.track }}",
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true
    )
  end
end
