package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/YOUR_GITHUB_ORG/backstage-idp-starter/cli/internal/backstage"
	"github.com/spf13/cobra"
)

var (
	ctxService string
	ctxTargets []string
	ctxDryRun  bool
	ctxURL     string
	ctxToken   string
	ctxEnv     string
)

var contextCmd = &cobra.Command{
	Use:   "context",
	Short: "Manage AI-tool project context",
}

var contextInjectCmd = &cobra.Command{
	Use:   "inject",
	Short: "Push a service's catalog metadata into CLAUDE.md / Cursor rules",
	Long: `Fetches a component's catalog entity from Backstage (SLO targets, cost budget,
scorecard, on-call, security scan keys, TechDocs ref) and writes it as an idempotent
fenced block into CLAUDE.md (and/or .cursor/rules), so AI coding tools pick up
live platform context without hand-copying annotations.`,
	Example: `  idp context inject --service hello-service
  idp context inject --service hello-service --target cursor
  idp context inject --service hello-service --dry-run`,
	RunE: runContextInject,
}

func init() {
	contextCmd.AddCommand(contextInjectCmd)
	contextInjectCmd.Flags().StringVar(&ctxService, "service", "", "Component name (defaults to catalog-info.yaml in the current directory)")
	contextInjectCmd.Flags().StringSliceVar(&ctxTargets, "target", []string{"claude"}, "Where to write context: claude | cursor (repeatable)")
	contextInjectCmd.Flags().BoolVar(&ctxDryRun, "dry-run", false, "Print the context block without writing files")
	contextInjectCmd.Flags().StringVar(&ctxURL, "backstage-url", "", "Backstage base URL")
	contextInjectCmd.Flags().StringVar(&ctxToken, "token", "", "Backstage service token")
	contextInjectCmd.Flags().StringVar(&ctxEnv, "env", envLocal, fmt.Sprintf("Target environment: %s | %s", envLocal, envAWS))
}

const (
	contextBlockStart = "<!-- idp:context:start -->"
	contextBlockEnd   = "<!-- idp:context:end -->"
)

func runContextInject(cmd *cobra.Command, _ []string) error {
	name := ctxService
	if name == "" {
		name = serviceNameFromCatalogInfo(".")
	}
	if name == "" {
		return fmt.Errorf("--service is required (no catalog-info.yaml found in the current directory)")
	}

	url := resolveBackstageURL(ctxEnv, ctxURL, rootDir())
	token := resolveToken(ctxEnv, ctxToken, rootDir())
	client := backstage.NewClient(url, token)

	entity, err := client.GetEntity(cmd.Context(), "component", "default", name)
	if err != nil {
		return fmt.Errorf("fetching component %q: %w", name, err)
	}

	block := renderContextBlock(name, entity)

	if ctxDryRun {
		fmt.Println(block)
		return nil
	}

	for _, target := range ctxTargets {
		var path string
		switch target {
		case "claude":
			path = filepath.Join(rootDir(), "CLAUDE.md")
		case "cursor":
			path = filepath.Join(rootDir(), ".cursor", "rules", "platform-context.mdc")
		default:
			return fmt.Errorf("unknown --target %q (must be claude or cursor)", target)
		}
		if err := writeContextBlock(path, block); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		fmt.Printf("[idp] Updated %s\n", path)
	}
	return nil
}

// renderContextBlock builds the fenced markdown block from entity annotations.
func renderContextBlock(name string, entity map[string]any) string {
	var b strings.Builder
	b.WriteString(contextBlockStart + "\n")
	b.WriteString(fmt.Sprintf("<!-- Auto-generated by `idp context inject --service %s`. Do not edit by hand; re-run to refresh. -->\n\n", name))
	b.WriteString(fmt.Sprintf("## Platform context: %s\n\n", name))

	metadata, _ := entity["metadata"].(map[string]any)
	if metadata != nil {
		if desc, ok := metadata["description"].(string); ok && desc != "" {
			b.WriteString(desc + "\n\n")
		}
	}

	annotations := map[string]any{}
	if metadata != nil {
		if a, ok := metadata["annotations"].(map[string]any); ok {
			annotations = a
		}
	}

	keys := make([]string, 0, len(annotations))
	for k := range annotations {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if len(keys) > 0 {
		b.WriteString("| Annotation | Value |\n|---|---|\n")
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("| `%s` | %v |\n", k, annotations[k]))
		}
		b.WriteString("\n")
	}

	b.WriteString(contextBlockEnd)
	return b.String()
}

// writeContextBlock replaces the fenced block in path, or appends/creates it.
func writeContextBlock(path, block string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		existing = []byte{}
	}

	content := string(existing)
	re := regexp.MustCompile(`(?s)` + regexp.QuoteMeta(contextBlockStart) + `.*?` + regexp.QuoteMeta(contextBlockEnd))
	if re.MatchString(content) {
		content = re.ReplaceAllString(content, block)
	} else {
		if content != "" && !strings.HasSuffix(content, "\n\n") {
			content = strings.TrimRight(content, "\n") + "\n\n"
		}
		content += block + "\n"
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

// serviceNameFromCatalogInfo reads metadata.name out of dir/catalog-info.yaml
// without a YAML dependency.
func serviceNameFromCatalogInfo(dir string) string {
	data, err := os.ReadFile(filepath.Join(dir, "catalog-info.yaml"))
	if err != nil {
		return ""
	}
	inMetadata := false
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "metadata:" {
			inMetadata = true
			continue
		}
		if inMetadata {
			if v, ok := strings.CutPrefix(trimmed, "name:"); ok {
				return strings.Trim(strings.TrimSpace(v), `"'`)
			}
			if len(line) > 0 && line[0] != ' ' && line[0] != '\t' {
				inMetadata = false
			}
		}
	}
	return ""
}
