apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: services-dev
    backstage.io/adr-location: https://github.com/${{ values.githubOrg }}/${{ values.repoName }}/tree/main/docs/adr
    backstage.io/runbook-url: https://github.com/${{ values.githubOrg }}/${{ values.repoName }}/blob/main/docs/runbooks/service.md
    cost-center: "${{ values.costCenter }}"
  links:
    - title: Grafana Dashboard
      url: http://grafana.idp.local/d/idp-services/idp-services-overview
      icon: dashboard
    - title: ArgoCD App
      url: http://argocd.idp.local/applications/${{ values.name }}-dev
      icon: web
    - title: Runbook
      url: https://github.com/${{ values.githubOrg }}/${{ values.repoName }}/blob/main/docs/runbooks/service.md
      icon: help
spec:
  type: website
  lifecycle: development
  owner: ${{ values.owner }}
  system: internal-developer-platform
