replicaCount: 1

image:
  repository: ghcr.io/${{ values.githubOrg }}/${{ values.name }}
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

env:
  - name: ENVIRONMENT
    value: dev

metrics:
  enabled: true
  port: metrics
  path: /metrics

extraPorts:
  - name: metrics
    port: 9113
    targetPort: 9113

extraContainers:
  - name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:1.3.0
    args:
      - --nginx.scrape-uri=http://localhost/nginx_status
    ports:
      - name: metrics
        containerPort: 9113
    livenessProbe:
      httpGet:
        path: /metrics
        port: 9113
      initialDelaySeconds: 5
      periodSeconds: 15
    readinessProbe:
      httpGet:
        path: /metrics
        port: 9113
      initialDelaySeconds: 3
      periodSeconds: 10
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 100m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop: [ALL]
