apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-kafka
spec:
  package: xpkg.upbound.io/upbound/provider-aws-kafka:v1.18.0
  runtimeConfigRef:
    name: provider-aws-irsa
