apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    grafana/alert-label-selector: "service=${{ values.name }}"
    pagerduty.com/service-id: "${{ values.pagerdutyServiceId }}"
    idp.io/quality-gates: "coverage"
    jira/project-key: "${{ values.jiraProjectKey }}"
  tags:
    - chaos
    - chaos-mesh
    - resilience
    - testing
spec:
  type: test-suite
  lifecycle: production
  owner: ${{ values.owner }}
  system: internal-developer-platform
{%- if values.targetService %}
  dependsOn:
    - ${{ values.targetService }}
{%- endif %}
