apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.serviceName }}-db
  description: PostgreSQL RDS database for ${{ values.serviceName }}
  annotations:
    backstage.io/managed-by-location: url:https://github.com/moatazeldebsy/backstage-idp-starter/blob/main/services/${{ values.serviceName }}/k8s/database/
  tags:
    - database
    - postgresql
    - aws-rds
spec:
  type: database
  owner: ${{ values.owner }}
  system: internal-developer-platform
