apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-svc
  description: Auto-scaffolded nodejs service
  annotations:
    github.com/project-slug: moatazeldebsy/order-svc
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app.kubernetes.io/instance=order-svc
    backstage.io/kubernetes-namespace: services
spec:
  type: service
  lifecycle: development
  owner: platform-team
  system: internal-developer-platform
