apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backstage-mlplatform
  namespace: ml-platform
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backstage-mlplatform
  namespace: ml-platform
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: backstage
roleRef:
  kind: Role
  name: backstage-mlplatform
  apiGroup: rbac.authorization.k8s.io
