apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - k6
    - performance
    - load-testing
spec:
  type: test-suite
  lifecycle: production
  owner: ${{ values.owner }}
  system: internal-developer-platform
{%- if values.targetService %}
  dependsOn:
    - ${{ values.targetService }}
{%- endif %}
