sonar.projectKey=moatazeldebsy_backstage-platform-template
sonar.organization=moatazeldebsy
sonar.projectName=IDP Backstage App
sonar.host.url=https://sonarcloud.io

sonar.sources=packages/app/src,packages/backend/src
sonar.tests=packages/app/src,packages/backend/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.spec.tsx,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/dist-types/**,**/coverage/**,**/e2e-tests/**,**/__mocks__/**

sonar.javascript.lcov.reportPaths=packages/app/coverage/lcov.info,packages/backend/coverage/lcov.info
sonar.testExecutionReportPaths=packages/app/junit.xml,packages/backend/junit.xml

sonar.sourceEncoding=UTF-8
