replicaCount: 1

image:
  repository: ghcr.io/${{ values.githubOrg }}/${{ values.name }}
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: ${{ values.port }}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
  hosts:
    - host: ${{ values.name }}-dev.idp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "${{ values.port }}"
  prometheus.io/path: "/metrics"

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

env:
  - name: LOG_LEVEL
    value: info
  - name: ENVIRONMENT
    value: dev
  - name: LLM_PROVIDER
    value: "${{ values.llmProvider }}"
  - name: LLM_MODEL
    value: "${{ values.llmModel }}"
  - name: MLFLOW_TRACKING_URI
    value: "http://mlflow.ml-platform.svc.cluster.local:5000"
  - name: MLFLOW_EXPERIMENT
    value: "${{ values.name }}"
  - name: OLLAMA_BASE_URL
    value: "http://host.docker.internal:11434"
