replicaCount: 1

image:
  repository: localhost:5003/flutter-platform-demo
  tag: "local"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: flutter-platform-demo.idp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

podLabels:
  team: "android-team"
  cost-center: "eng-mobile"
  environment: local
  app.kubernetes.io/part-of: internal-developer-platform

labels:
  backstage.io/kubernetes-id: flutter-platform-demo
