apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ${{ values.name }}-run-
  namespace: ml-platform
  labels:
    ml/job: ${{ values.name }}
    app.kubernetes.io/part-of: internal-developer-platform
spec:
  entrypoint: train
  serviceAccountName: argo-workflow

  # Override via argo submit --parameter
  arguments:
    parameters:
      - name: image-tag
        value: "latest"
      - name: n-estimators
        value: "100"
      - name: max-depth
        value: ""  # empty = unlimited

  templates:
    - name: train
      container:
        image: "ghcr.io/${{ values.githubOrg }}/${{ values.name }}:{{`{{workflow.parameters.image-tag}}`}}"
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "src.train"]
        env:
          - name: MLFLOW_TRACKING_URI
            value: "http://mlflow.ml-platform.svc.cluster.local:5000"
          - name: MLFLOW_EXPERIMENT_NAME
            value: "${{ values.mlflowExperiment }}"
          - name: MODEL_NAME
            value: "${{ values.name }}"
          - name: N_ESTIMATORS
            value: "{{`{{workflow.parameters.n-estimators}}`}}"
          - name: MAX_DEPTH
            value: "{{`{{workflow.parameters.max-depth}}`}}"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 2Gi
{% if values.schedule %}
---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: ${{ values.name }}-scheduled
  namespace: ml-platform
  labels:
    ml/job: ${{ values.name }}
spec:
  schedule: "${{ values.schedule }}"
  timezone: "UTC"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: train
    serviceAccountName: argo-workflow
    arguments:
      parameters:
        - name: image-tag
          value: "latest"
        - name: n-estimators
          value: "100"
        - name: max-depth
          value: ""
    templates:
      - name: train
        container:
          image: "ghcr.io/${{ values.githubOrg }}/${{ values.name }}:latest"
          imagePullPolicy: IfNotPresent
          command: ["python", "-m", "src.train"]
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.ml-platform.svc.cluster.local:5000"
            - name: MLFLOW_EXPERIMENT_NAME
              value: "${{ values.mlflowExperiment }}"
            - name: MODEL_NAME
              value: "${{ values.name }}"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
{% endif %}
