apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.repoName }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/runbook-url: https://github.com/${{ values.githubOrg }}/${{ values.repoName }}/blob/main/docs/runbook.md
  tags:
    - sdk
    - library
    - mobile
    - ${{ values.platform }}
spec:
  type: library
  lifecycle: development
  owner: ${{ values.owner }}
  system: internal-developer-platform
