replicaCount: 1

image:
  repository: ghcr.io/${{ values.githubOrg }}/${{ values.name }}
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: ${{ values.port }}

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podLabels:
  team: "${{ values.owner | replace('group:default/', '') | replace('user:default/', '') | replace(':', '-') | replace('/', '-') }}"
  cost-center: ${{ values.costCenter }}
  environment: dev

metrics:
  enabled: true
  path: /actuator/prometheus

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: ENVIRONMENT
    value: dev
