apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chaos-suite
  description: chaos test suite for hello-service
  annotations:
    github.com/project-slug: YOUR_GITHUB_ORG/chaos-suite
    backstage.io/techdocs-ref: dir:.
spec:
  type: test-suite
  lifecycle: production
  owner: qa-team
  system: internal-developer-platform
  dependsOn:
    - component:default/hello-service
