apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.bucketName }}
  description: S3 bucket ${{ values.bucketName }} in ${{ values.awsRegion }} — managed by Crossplane
  annotations:
    backstage.io/managed-by-location: url:https://github.com/moatazeldebsy/backstage-platform-template/blob/main/services/${{ values.ownerService }}/claims/${{ values.bucketName }}.yaml
  labels:
    aws-region: ${{ values.awsRegion }}
    provisioner: crossplane
  tags:
    - s3
    - storage
    - aws
    - crossplane
spec:
  type: storage
  owner: ${{ values.owner }}
  system: internal-developer-platform
  dependencyOf:
    - component:${{ values.ownerService }}
