sonar.projectKey=${{ values.githubOrg }}_${{ values.repoName }}
sonar.organization=${{ values.githubOrg }}
sonar.projectName=${{ values.name }}
sonar.host.url=https://sonarcloud.io

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*_test.dart
sonar.exclusions=**/.dart_tool/**,**/build/**

sonar.dart.coverage.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
