sonar.projectKey=${{ values.githubOrg }}_${{ values.repoName }}
sonar.organization=${{ values.githubOrg }}
sonar.projectName=${{ values.name }}
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/*.spec.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=junit.xml

sonar.sourceEncoding=UTF-8
