sonar.projectKey=${{ values.githubOrg }}_${{ values.name }}
sonar.organization=${{ values.githubOrg }}
sonar.projectName=${{ values.name }}

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.js,**/*.spec.ts,**/*.spec.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/*.spec.*

# LCOV coverage report from Jest (--coverage --coverageReporters=lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
