replicaCount: 1

image:
  repository: localhost:5003/pyth-demo-srv
  tag: local
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8005

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: pyth-demo-srv.idp.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

env:
  - name: LOG_LEVEL
    value: debug
  - name: ENVIRONMENT
    value: local

podLabels:
  team: "data-team"
  cost-center: "eng-platform"
  environment: local
  app.kubernetes.io/part-of: internal-developer-platform
