apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ values.serviceName }}-${{ values.secretKey | lower | replace("_", "-") }}
  namespace: services
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: ${{ values.serviceName }}-secrets
    creationPolicy: Merge
  data:
    - secretKey: ${{ values.secretKey }}
      remoteRef:
        key: ${{ values.secretPath }}
