sonar.projectKey=${{ values.githubOrg }}_${{ values.name }}
sonar.organization=${{ values.githubOrg }}
sonar.projectName=${{ values.name }}

sonar.sources=.
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/tests/**,**/*.pyc

# Coverage report from pytest-cov --cov-report=xml
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
