apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ values.serviceName }}-${{ values.secretKey | lower | replace('_', '-') }}
  namespace: services
  labels:
    app.kubernetes.io/name: ${{ values.serviceName }}
    app.kubernetes.io/managed-by: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ${{ values.serviceName }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: ${{ values.secretKey }}
      remoteRef:
        key: ${{ values.secretPathPrefix }}/${{ values.serviceName }}
        property: ${{ values.secretKey }}
