#!/usr/bin/env bash
# generate-slo-rules.sh — regenerate observability/slo/generated/ from the Sloth
# sources in observability/slo/.
#
# Each observability/slo/<name>-slos.yaml is a PrometheusServiceLevel, a Sloth
# CRD. No Sloth operator runs in-cluster, so nothing reads those files at
# runtime: bootstrap applies the committed PrometheusRule output in
# observability/slo/generated/<name>-slo-rules.yaml instead. Editing a source
# without regenerating silently did nothing (#314). This script is the "write"
# half of keeping them in step; the `slo-drift` CI job runs `--check`.
#
# Sloth is downloaded at a pinned version and verified by SHA-256, so the output
# is reproducible on any machine and in CI.
#
# Usage:
#   ./scripts/generate-slo-rules.sh            # rewrite every generated file
#   ./scripts/generate-slo-rules.sh --check    # report drift, write nothing (CI)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SLO_DIR="${REPO_ROOT}/observability/slo"
GEN_DIR="${SLO_DIR}/generated"

SLOTH_VERSION="v0.16.0"

CHECK=false
[[ "${1:-}" == "--check" ]] && CHECK=true

# ── Pinned sloth binary ───────────────────────────────────────────────────────
case "$(uname -s)-$(uname -m)" in
  Linux-x86_64)            asset=sloth-linux-amd64;  sha=1cecaa50853abbb3669a928612b523df8174d258ea6f2a3c8f048e5fc5af90b2 ;;
  Linux-aarch64|Linux-arm64) asset=sloth-linux-arm64; sha=7b570c465df3cc997e744dfcfcea83c3559bba6b12f4d6165994925419cbb41c ;;
  Darwin-arm64)            asset=sloth-darwin-arm64; sha=d9ee5967fd412f6592a0c5aec35f7f9f1fc4a2726eb25414a11815ca78185aa9 ;;
  Darwin-x86_64)           asset=sloth-darwin-amd64; sha=c62623ea730818ef611c82fd1318d9741cfde4717a6179ebd9e3649a3b8b6017 ;;
  *) echo "error: no pinned sloth build for $(uname -s)-$(uname -m)" >&2; exit 1 ;;
esac

sha256() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | awk '{print $1}'
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/idp-platform"
SLOTH="${CACHE_DIR}/sloth-${SLOTH_VERSION}-${asset}"
if [[ ! -x "$SLOTH" || "$(sha256 "$SLOTH")" != "$sha" ]]; then
  mkdir -p "$CACHE_DIR"
  echo "Downloading sloth ${SLOTH_VERSION} (${asset})..."
  curl -fsSL -o "${SLOTH}.tmp" \
    "https://github.com/slok/sloth/releases/download/${SLOTH_VERSION}/${asset}"
  if [[ "$(sha256 "${SLOTH}.tmp")" != "$sha" ]]; then
    rm -f "${SLOTH}.tmp"
    echo "error: checksum mismatch for ${asset} — refusing to run it" >&2
    exit 1
  fi
  chmod +x "${SLOTH}.tmp"
  mv "${SLOTH}.tmp" "$SLOTH"
fi

# ── Generate ──────────────────────────────────────────────────────────────────
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

drift=0
expected=()
shopt -s nullglob
for src in "${SLO_DIR}"/*-slos.yaml; do
  name="$(basename "$src" -slos.yaml)"
  rel_src="observability/slo/$(basename "$src")"
  out_name="${name}-slo-rules.yaml"
  expected+=("$out_name")

  {
    echo "# GENERATED by: scripts/generate-slo-rules.sh (sloth ${SLOTH_VERSION} generate -i ${rel_src})"
    echo "# Do not edit — change the PrometheusServiceLevel source and re-run the script."
    echo "# Vendored so bootstrap can apply SLOs without requiring the sloth binary."
    "$SLOTH" generate -i "$src" 2>/dev/null
  } > "${WORK}/${out_name}"

  if $CHECK; then
    if [[ ! -f "${GEN_DIR}/${out_name}" ]]; then
      echo "MISSING  observability/slo/generated/${out_name} (source: ${rel_src})"
      drift=1
    elif ! diff -u "${GEN_DIR}/${out_name}" "${WORK}/${out_name}" > "${WORK}/${out_name}.diff"; then
      echo "DRIFT    observability/slo/generated/${out_name} does not match ${rel_src}:"
      sed 's/^/    /' "${WORK}/${out_name}.diff" | head -40
      drift=1
    else
      echo "ok       observability/slo/generated/${out_name}"
    fi
  else
    mkdir -p "$GEN_DIR"
    cp "${WORK}/${out_name}" "${GEN_DIR}/${out_name}"
    echo "wrote    observability/slo/generated/${out_name}"
  fi
done

# A generated file whose source was deleted is still applied by bootstrap.
for gen in "${GEN_DIR}"/*-slo-rules.yaml; do
  base="$(basename "$gen")"
  if [[ ! " ${expected[*]} " == *" ${base} "* ]]; then
    echo "ORPHAN   observability/slo/generated/${base} has no source in observability/slo/"
    drift=1
  fi
done

if $CHECK && [[ $drift -ne 0 ]]; then
  echo
  echo "SLO rules are out of date. Run ./scripts/generate-slo-rules.sh and commit observability/slo/generated/." >&2
  exit 1
fi
