// Generated by IDP golden path — replace with real tests for ${{ values.repoName }}

describe('${{ values.repoName }}', () => {
  test('placeholder: replace with real assertions', () => {
    expect(true).toBe(true);
  });

  test('example: pure function assertion', () => {
    const add = (a, b) => a + b;
    expect(add(2, 3)).toBe(5);
  });
});
