apiVersion: v1
kind: Namespace
metadata:
  name: team-awesome-team
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    team: awesome-team
    cost-center: CC-1234
    managed-by: idp-backstage
