apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name }} E2E Suite
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - qa
    - playwright
    - e2e
    - testing
spec:
  type: e2e-test-suite
  lifecycle: production
  owner: ${{ values.owner }}
  system: internal-developer-platform
