replicaCount: 1

image:
  repository: localhost:5003/${{ values.name }}
  tag: "local"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: ${{ values.port }}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: ${{ values.name }}.idp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "${{ values.port }}"
  prometheus.io/path: "/metrics"

podLabels:
  team: ${{ values.owner }}
  cost-center: ${{ values.costCenter }}
  environment: local

metrics:
  enabled: true

env:
  - name: LOG_LEVEL
    value: debug
  - name: ENVIRONMENT
    value: local

labels:
  backstage.io/kubernetes-id: ${{ values.name }}
