sonar.projectKey=${{ values.githubOrg }}_${{ values.repoName }}
sonar.organization=${{ values.githubOrg }}
sonar.projectName=${{ values.name }}
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=junit.xml

sonar.sourceEncoding=UTF-8
