replicaCount: 1

image:
  repository: localhost:5003/hello-go-service
  tag: "local"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: hello-go-service.idp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/metrics"

podLabels:
  team: "backend-team"
  cost-center: "eng-platform"
  environment: local
  app.kubernetes.io/part-of: internal-developer-platform

metrics:
  enabled: true

env:
  - name: LOG_LEVEL
    value: debug
  - name: ENVIRONMENT
    value: local

labels:
  backstage.io/kubernetes-id: hello-go-service
