replicaCount: 1

image:
  repository: ghcr.io/${{ values.githubOrg }}/${{ values.name }}
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ${{ values.name }}-dev.idp.local
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

env:
  - name: ENVIRONMENT
    value: dev

podLabels:
  team: "${{ values.owner | replace('group:default/', '') | replace('user:default/', '') }}"
  cost-center: "${{ values.costCenter }}"
  environment: dev
  app.kubernetes.io/part-of: internal-developer-platform
